from turtle import *

speed(0)

def ok():
    fillcolor("yellow")
    begin_fill()
    circle(30)
    end_fill()
    color("black")
    penup()
    left(90)
    forward(35)
    left(90)
    forward(15)
    right(180)
    pendown()
    forward(15)
    penup()
    forward(5)
    pendown()
    forward(15)
    penup()
    right(90)
    forward(15)
    right(90)
    forward(10)
    pendown()
    forward(20)
    penup()
    left(90)
    forward(20)
    left(90)
    forward(10)
    pendown()

def grin():
    fillcolor("yellow")
    begin_fill()
    circle(30)
    end_fill()
    color("black")
    penup()
    left(90)
    forward(35)
    left(90)
    forward(10)
    right(180)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    forward(20)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    right(90)
    forward(10)
    pendown()
    fillcolor("white")
    begin_fill()
    for i in range(2):
        forward(10)
        right(90)
        forward(20)
        right(90)
    end_fill()
    forward(5)
    right(90)
    forward(20)
    right(90)
    forward(5)
    right(90)
    forward(5)
    right(90)
    forward(10)
    left(90)
    forward(5)
    left(90)
    forward(10)
    right(90)
    forward(5)  
    right(90)
    forward(10)
    penup()
    forward(15)
    right(90)
    forward(15)
    right(180)
    forward(10)
    pendown()

def surprised():
    fillcolor("yellow")
    begin_fill()
    circle(30)
    end_fill()
    
    color("black")
    penup()
    left(90)
    forward(35)
    left(90)
    forward(10)
    right(180)
    pendown()
    
    begin_fill()
    circle(5)
    end_fill()
    
    penup()
    forward(20)
    pendown()
    
    begin_fill()
    circle(5)
    end_fill()
    
    penup()
    right(90)
    forward(10) 
    right(90)
    forward(10)
    pendown()
    fillcolor("white")
    begin_fill()
    circle(9)
    end_fill()
    
    penup()
    left(90)
    forward(25)
    left(90)
    pendown()

def sleepy():
    surprised()
    penup()
    forward(10)
    pendown()
    color('Black')
    write("Z Z Z", font = ('Arial', 10, 'bold'))

def move_next():
    penup()
    forward(100)
    pendown()

penup()
backward(550)
pendown()

inp=numinput("Emoji","Which emoji should get printed?\n1. Annoyed\n2. Surprised\n3. Grinning\n4. Sleepy\n0. Quit")

while (inp != 0):
    if(inp == 1):
        ok()
        move_next()
    elif(inp == 2):
        surprised()
        move_next()
    elif(inp == 3):
        grin()
        move_next()
    elif(inp == 4):
        sleepy()
        move_next()
    else:
        print("Incorrect input")
    inp=numinput("Emoji","Which emoji should get printed?\n1. Annoyed\n2. Surprised\n3. Grinning\n4. Sleepy\n0. Quit")
    
done()